

services:
  # 1. Servicio de la Base de Datos (postgres)
  # Este es el mismo contenedor que ya estabas corriendo, pero mejor definido.
  postgres:
    image: postgres:14-alpine
    container_name: conteinerDBFastApi_compose
    restart: always
    environment:
      # Los mismos valores de tu comando docker run
      POSTGRES_USER: kcire
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: dbFastApi
    ports:
      # Exponemos el puerto para que puedas conectarte desde tu máquina
      - "5433:5432"
    volumes:
      # Usamos el mismo volumen nombrado que creaste para mantener tus datos
      - fastapi_db_volume:/var/lib/postgresql/data
    networks:
      - fastapi-network
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U kcire -d dbFastApi"]
      interval: 5s
      timeout: 5s
      retries: 5
  
  # 2. Servicio de la Aplicación Python (web)
  web:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - fastapi-network

networks:
  fastapi-network:

volumes:
  fastapi_db_volume:

